package petshop;

// Creating an enum class for the list of services. 

public enum ServiceType {
	BATH,
	GROOMING,
	HEAVY_GROMMING,
	NAIL_TRIMMING,
	EAR_CLEANING,
	TEETH_BRUSHING,
	HIDRATATION_TREATMENT,
	FLEA_TREATMENT,
	VETERINARY_CONSULTATION,
	VACCINATION,
	LABORATORY_TESTS,
	MICROCHIP_IDENTIFICATION,
	PET_FOOD_SALES,
	
}
