CREATE TABLE client(
client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
name varchar2(100) NOT NULL,
phone varchar2(20) NOT NULL,
address varchar2(100) NOT NULL,
email varchar2(100) NOT null
);

CREATE TABLE animal(
animal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
client_id NUMBER NOT NULL,
name varchar2(40) NOT NULL,
age number NOT NULL,
sex varchar2(10) NOT NULL,
breed varchar2(50) NOT NULL,
species varchar2(50) NOT NULL,
weight number NOT NULL,
CONSTRAINT fk_animal_client FOREIGN KEY (client_id) REFERENCES client(client_id)
);

CREATE TABLE servicetype(
service_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar2(50) NOT NULL,
description varchar2(500),
price number(10,2) NOT NULL,
duration number(5) NOT NULL -- duration minutes
);